mode: backtest # backtest, live
exchange: okx
start_date: 2025-04-20
end_date: 2025-05-01
primary_interval: 1h
initial_cash: 100000
margin_requirement: 0.0
show_reasoning: false
show_agent_graph: true
signals:
  intervals: ["30m", "1h", "4h"]
  tickers: ["BTC/USDT", "ETH/USDT"]
  strategies: ['MacdStrategy']
# , "RSIStrategy"]
model:
  name: "gpt-4o"
  provider: "openai"
#  base_url: "https://api.openai.com/v1"  #
